version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: xcodebuild test -sdk macosx10.13 -project Atlas.xcodeproj/ -scheme Atlas -destination 'platform=OS X,arch=x86_64' 
