.TH git-annex-initremote 1
.SH NAME
git-annex-initremote \- creates a special (non\-git) remote
.PP
.SH SYNOPSIS
git annex initremote \fBname type=value [param=value ...]\fP
.PP
.SH DESCRIPTION
Creates a new special remote, and adds it to \fB.git/config\fP.
.PP
Example Amazon S3 remote:
.PP
 git annex initremote mys3 type=S3 encryption=hybrid keyid=me@example.com datacenter=EU
.PP
Many different types of special remotes are supported by git-annex.
For a list and details, see <https://git-annex.branchable.com/special_remotes/>
.PP
The remote's configuration is specified by the parameters passed
to this command. Different types of special remotes need different
configuration values. The command will prompt for parameters as needed.
.PP
All special remotes support encryption. You can specify
\fBencryption=none\fP to disable encryption, or specify
\fBencryption=hybrid keyid=$keyid ...\fP to specify a GPG key id (or an email
address associated with a key). For details about ways to configure
encryption, see <https://git-annex.branchable.com/encryption/>
.PP
If you anticipate using the new special remote in other clones of the
repository, you can pass "autoenable=true". Then when git-annex\-init(1)
is run in a new clone, it will attempt to enable the special remote. Of
course, this works best when the special remote does not need anything
special to be done to get it enabled.
.PP
Normally, git-annex generates a new UUID for the new special remote.
If you want to, you can specify a UUID for it to use, by passing a
uuid=whatever parameter. This can be useful in some situations, eg when the
same data can be accessed via two different special remote backends.
But if in doubt, don't do this.
.PP
.SH OPTIONS
.IP "\fB\-\-fast\fP"
.IP
When initializing a remote that uses encryption, a cryptographic key is
created. This requires sufficient entropy. If initremote seems to hang
or take a long time while generating the key, you may want to Ctrl\-c it
and re\-run with \fB\-\-fast\fP, which causes it to use a lower\-quality source of
randomness. (Ie, /dev/urandom instead of /dev/random)
.IP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-enableremote(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

