.TH git-annex-smudge 1
.SH NAME
git-annex-smudge \- git filter driver for git-annex
.PP
.SH SYNOPSIS
git annex smudge [\-\-clean] file
.PP
.SH DESCRIPTION
This command lets git-annex be used as a git filter driver which lets
annexed files in the git repository to be unlocked at all times, instead
of being symlinks.
.PP
When adding a file with \fBgit add\fP, the annex.largefiles config is
consulted to decide if a given file should be added to git as\-is,
or if its content are large enough to need to use git-annex.
.PP
The git configuration to use this command as a filter driver is as follows.
This is normally set up for you by git-annex init, so you should
not need to configure it manually.
.PP
 [filter "annex"]
         smudge = git-annex smudge %f
         clean = git-annex smudge \-\-clean %f
.PP
To make git use that filter driver, it needs to be configured in
the \fB.gitattributes\fP file or in \fB.git/info/attributes\fP. The latter
is normally configured when a repository is initialized, with the following
contents:
.PP
 * filter=annex
 .* !filter
.PP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

