.TH git-annex-merge 1
.SH NAME
git-annex-merge \- automatically merge changes from remotes
.PP
.SH SYNOPSIS
git annex merge
.PP
.SH DESCRIPTION
This performs the same merging (and merge conflict resolution)
that is done by the sync command, but without pushing or pulling any
data.
.PP
When annex.resolvemerge is set to false, merge conflict resolution
will not be done.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-sync(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

