.TH git-annex-indirect 1
.SH NAME
git-annex-indirect \- switch repository to indirect mode
.PP
.SH SYNOPSIS
git annex indirect
.PP
.SH DESCRIPTION
Switches a repository back from direct mode to the default, indirect
mode.
.PP
Note that the direct mode/indirect mode distinction is removed in v6
git-annex repositories.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-direct(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

